name: movie_omdbid_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
        - asset: assets/fonts/RedHatDisplay-Italic.ttf
        - asset: assets/fonts/RedHatDisplay-BoldItalic.ttf
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
        - asset: assets/fonts/RedHatDisplay-MediumItalic.ttf
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf
        - asset: assets/fonts/RedHatDisplay-SemiBoldItalic.ttf
    
    - family: RacingSansOne
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf 
