name: movie_explorer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  bloc: ^9.2.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.1.1
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
        - asset: assets/fonts/RedHatDisplay-Italic.ttf
        - asset: assets/fonts/RedHatDisplay-BoldItalic.ttf
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
        - asset: assets/fonts/RedHatDisplay-MediumItalic.ttf
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf
        - asset: assets/fonts/RedHatDisplay-SemiBoldItalic.ttf

    - family: RacingSansOne
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf
